theme: jekyll-theme-minimal
title: Mike Jacobi
description: >
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-GRPRD4R0DC"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-GRPRD4R0DC');
  </script>

  <br />
  mikerjacobi@gmail.com
  <br />
  Machine Learning Engineer, Charmed AI
  <br />
  <a href="/resume.pdf">Resume PDF</a> * 
  <a href="https://www.linkedin.com/in/mikerjacobi/">LinkedIn</a> 
logo: /assets/portrait.png
