theme: jekyll-theme-minimal
title: Jacobra
description: >
    <a href="/assets/resume.pdf">View my Resume</a>
    
    <a href="https://www.linkedin.com/in/mikerjacobi/">View my Linked In</a>

logo: /assets/portrait.jpg
is_project_page: false

