theme: jekyll-theme-minimal
title: Mike Jacobi
description: >
    <br />
    mikerjacobi@gmail.com
    <br />
    Senior Software Engineer, Linden Lab
    <br />
    <a href="/resume.html">Resume</a> *
    <a href="https://github.com/mikerjacobi">Github</a> *
    <a href="https://www.linkedin.com/in/mikerjacobi/">LinkedIn</a> 
logo: /assets/portrait.png
google_analytics: UA-146509008-2
