theme: jekyll-theme-minimal
title: Mike Jacobi
description: >
    <br />
    mikerjacobi@gmail.com
    <br />
    Machine Learning Engineer, Charmed AI
    <br />
    Senior Engineering Manager, Tilia
    <br />
    <a href="/resume.pdf">Resume PDF</a> * 
    <a href="https://github.com/mikerjacobi">Github</a> *
    <a href="https://www.linkedin.com/in/mikerjacobi/">LinkedIn</a> 
logo: /assets/portrait.png
google_analytics: UA-72654822-2
